### ISSUE TITLE
Write a README.md file with examples

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/GADM.jl#20]
Try to follow the convention of this README: https://github.com/JuliaEarth/ExtremeStats.jl

An installation and an usage section at least. :+1:

**Comment by juliohm** [comment]
This is a package from another MLH fellow last year who did really well: https://github.com/JuliaClimate/CDSAPI.jl

**Comment by juliohm** [comment]
Before we close this, it would be nice to add somewhere in the README that these are the coordinates we get from the GADM website:
```
The coordinate reference system is longitude/latitude and the WGS84 datum.
```

**Comment by zerefwayne** [comment]
- [x] Add coordinate reference system
- [ ] Display plot of India
- [x] Add API for coordinates and its response
- [x] Add GADM License Link

**Comment by juliohm** [comment]
Also, we need to update the README to reflect the fact that now get and coordinates always return a MultiPolygon.

**Comment by juliohm** [comment]
@zerefwayne can you fix this issue? I think it is a quick fix and an important one.

**Comment by zerefwayne** [comment]
@juliohm I'll properly work on the README after merging the `get` refactor PR.

**Comment by juliohm** [comment]
I think we are ready now to update the README :) Please submit a PR with the readme changes and I can provide feedback :+1:

**Comment by juliohm** [comment]
Fixed on master :+1:
