### ISSUE TITLE
Add GADM_ prefix to downloaded folders

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GADM.jl#28]
Quite a minor point, but I noticed that the country codes are directly placed under the datadeps folder:
```
c:\Users\visser_mn\.julia\datadeps\IND\
c:\Users\visser_mn\.julia\datadeps\VAT\
```

Perhaps it would be better to keep them together under a GADM directory, such that if we want we can more easily delete them, because they won't be mixed with other DataDeps data?
```
c:\Users\visser_mn\.julia\datadeps\GADM\IND\
c:\Users\visser_mn\.julia\datadeps\GADM\VAT\
```

**Comment by zerefwayne** [comment]
It is not possible to store them in a separate directory. What do you think
of storing them as GADM_IND instead?

**Comment by juliohm** [comment]
@zerefwayne are you sure that DataDeps.jl doesn't allow customizing a root folder for the downloads?

**Comment by zerefwayne** [comment]
I went through the codebase and documentation but was unable to find
anything related to it.

**Comment by juliohm** [comment]
In this case, I think we need a separate PR to re-add the `GADM_` prefix you had originall. Let's handle it after you finish the other PRs.

**Comment by juliohm** [comment]
If DataDeps.jl already handles conflicts of existing folders, we don't even need to think about adding the prefix though. It doesn't solve the issue that @visr pointed out though. Ideally we would be able to put every country on a common root folder.

**Comment by visr** [comment]
Yeah I tried looking into it a bit as well, but it seems there is no good way of putting it together, without downloading all countries. The GADM_ prefix is a good suggestion.
