### ISSUE TITLE
Activate Travis CI + Codecov

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/GADM.jl#29]
@visr is Travis CI activated in JuliaGeo? The badges are pointing to an inactive build.

**Comment by zerefwayne** [comment]
@juliohm I think I need to fix these URLs of the badges and revisit the Codecov and TravisCI dashboard.

I did it when we switched to GADM.jl, inbuilt redirection doesn't work well with badges.

**Comment by visr** [comment]
Yeah I think that's it. Travis is also used in several other JuliaGeo repos, like https://travis-ci.org/github/JuliaGeo/LibGEOS.jl. Though I guess some of that has to be migrated to Travis.com now (or GitHub actions).

**Comment by juliohm** [comment]
I am asking it because I updated the badges and the links are pointing to invalid Travis builds. It would be nice to double check.

**Comment by visr** [comment]
Ok, now it works. I see it was on .com, and that was not yet enabled, only .org.

**Comment by zerefwayne** [comment]
Since it's working properly now, I'm closing this.
