### ISSUE TITLE
Update to ArchGDAL.jl v0.7

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/GADM.jl#37]
@zerefwayne any chance you have some free time to try update this package to the latest stable version of ArchGDAL.jl?

Here is a relevant discussion: https://github.com/yeesian/ArchGDAL.jl/issues/210

**Comment by zerefwayne** [comment]
Sure @juliohm, I'll have a look this weekend!

**Comment by juliohm** [comment]
Thank you @zerefwayne , that would be super helpful! After you update GADM.jl I will be able to update GeoTables.jl.

**Comment by juliohm** [comment]
@zerefwayne did you have time to look into this?

**Comment by zerefwayne** [comment]
Really swamped up with work right now. For sure, I'll do it by this weekend. Apologies for the delay.
