### ISSUE TITLE
Poster on JuliaCon without mention to package authors

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/GADM.jl#38]
@zerefwayne someone is presenting a poster on the GADM.jl package in this year's JuliaCon, are you aware of it? https://pretalx.com/juliacon2021/talk/KAJGA9/ The abstract doesn't mention your name.

**Comment by zerefwayne** [comment]
No, I wasn't contacted regarding this.

**Comment by juliohm** [comment]
I asked in the JuliaCon channel on slack to see what we can do. I am
assuming good intentions from the speaker but it is definitely not good to
not have your name there in the abstract.

**Comment by zerefwayne** [comment]
Thank you for pointing this out though! I'll get in touch with the team on JuliaCon channel.

**Comment by juliohm** [comment]
The issue has been addressed by the JuliaCon committee.
