### ISSUE TITLE
DataDeps warning when running `get`

### ISSUE THREAD

**Issue by asinghvi17** [JuliaGeo/GADM.jl#65]
```julia
GADM.get("JPN") # first run
```
yields a warning:
```
┌ Warning: Checksum not provided, add to the Datadep Registration the following hash line
│   hash = "a7d0955dfd9215d6b21cff3f5b7bf09b02c3b64290e7b6ac1b357b7789f45e03"
└ @ DataDeps ~/.julia/packages/DataDeps/Y2lje/src/verification.jl:44
```

I get similar errors for every other country.  This should probably be resolved in the registration block here:

https://github.com/JuliaGeo/GADM.jl/blob/606b61a9ce6fa7b3e4258ea12e60aa18bf30c3ba/src/GADM.jl#L64-L69

**Comment by juliohm** [comment]
If the hash is fixed per ID, then a dictionary can be introduced in the code for lookup. PRs are welcome.
